export const services = [
  {
    name: 'direction',
    service: 'Fitness Direction',
    price: '$149 one-time',
    description: 'Not sure where to start? I\'ll assess where you are, identify the gaps, and build you a personalized roadmap. Includes custom program, exercise video library, and a strategy call to make sure you have everything you need to succeed — no ongoing commitment.',
    bookingLink: 'https://cal.com/elmarfitness/personal-training-session',
    bookingLabel: 'Get Your Direction',
    image: '/training.png',
    classification: 'in-person',
    highlights: ['Custom workout program', 'Exercise video library', '1 strategy call', '90-day plan'],
  },
  {
    name: 'guide',
    service: 'Fitness Guide',
    price: '$199/month',
    description: 'You\'ve got the plan — now let\'s make sure you stick with it. I provide custom programs, bi-weekly check-ins, progress tracking, and adjustments along the way. Perfect for people who want accountability without weekly sessions.',
    bookingLink: 'https://cal.com/elmarfitness/partner-training-session',
    bookingLabel: 'Start Guiding',
    image: '/partner.png',
    classification: 'in-person',
    highlights: ['Custom program + updates', 'Bi-weekly check-ins', 'App access', 'Messaging support'],
  },
  {
    name: 'partner',
    service: 'Training Partner',
    price: '$299/month',
    description: 'Full coaching for serious athletes who want ongoing support. Weekly calls, unlimited messaging, custom programming, nutrition guidance, and form reviews. We\'ll work together to hit your goals — whatever it takes.',
    bookingLink: 'https://cal.com/elmarfitness/online-coaching-call',
    bookingLabel: 'Partner Up',
    image: '/online.png',
    classification: 'online',
    highlights: ['Weekly video calls', 'Unlimited messaging', 'Custom programming', 'Nutrition coaching'],
  },
  {
    name: 'meal-plan',
    service: 'Meal Planning',
    price: '$100/month',
    description: 'No starving, no fad diets. I build meal plans that fit your lifestyle, preferences, and goals — whether that\'s losing fat, building muscle, or just eating better. Based on your TDEE, food preferences, and schedule.',
    bookingLink: 'https://cal.com/elmarfitness/nutrition-meal-planning-call',
    bookingLabel: 'Get a Meal Plan',
    image: '/meal.png',
    classification: 'online',
    highlights: ['Personalized macros', 'Flexible dieting', 'Grocery lists', 'Recipe suggestions'],
  },
];
