export const services = [
  {
    name: '1-1',
    service: '1-on-1 Training',
    price: 'As low as $60/session',
    description: 'Join me for personalized training sessions where I focus on your unique fitness goals. As your sole trainer, I`ll guide you through workouts designed for physique enhancement, performance improvement, or overall wellness.',      
    bookingLink: 'https://cal.com/elmarfitness/personal-training-session',
    bookingLabel: 'Schedule a Session',
    image: '/training.png',
    classification: 'in-person',
  },
  {
    name: 'partner',
    service: 'Partner Training',
    price: 'As low as $80/session',
    description: 'Experience the synergy of partner training under my guidance. I`ll tailor sessions to both of your needs, combining solo and joint exercises for a balanced and effective workout.',      
    bookingLink: 'https://cal.com/elmarfitness/partner-training-session',
    bookingLabel: 'Schedule a Session',
    image: '/partner.png',
    classification: 'in-person',
  },
  {
    name: 'online-coaching',
    service: 'Online Coaching',
    price: 'As low as $150/month',
    description: 'With my online coaching, enjoy the flexibility of training anywhere. I provide custom workout plans, nutritional advice, and regular progress check-ins, ensuring a comprehensive virtual training experience.',      
    bookingLink: 'https://cal.com/elmarfitness/online-coaching-call',
    bookingLabel: 'Schedule a Call',
    image: '/online.png',
    classification: 'online',
  },
  {
    name: 'nutrition',
    service: 'Meal Planning',
    price: ' As low as $100/month',
    description: 'Let me craft a meal plan that aligns with your fitness targets. My approach considers your dietary needs, preferences, and goals, ensuring a balanced and enjoyable nutritional journey.',      
    bookingLink: 'https://cal.com/elmarfitness/nutrition-meal-planning-call',
    bookingLabel: 'Schedule a Call',
    image: '/meal.png',
    classification: 'online',
  },
];