export const services = [
  {
    name: '1-1',
    service: '1-on-1 Training',
    price: 'As low as $60/session',
    description: 'Science-backed training personalized to your body and goals. Using my Kinesiology background, I analyze your movement patterns and build programs that actually work — no cookie-cutter plans. Whether you\'re recovering from injury or chasing a PR, we\'ll train smart.',      
    bookingLink: 'https://cal.com/elmarfitness/personal-training-session',
    bookingLabel: 'Schedule a Session',
    image: '/training.png',
    classification: 'in-person',
    highlights: ['Movement assessment', 'Custom program design', 'Form correction', 'Progress tracking'],
  },
  {
    name: 'partner',
    service: 'Partner Training',
    price: 'As low as $80/session',
    description: 'Bring a friend and train smarter. I design complementary programs so both of you hit your goals — while keeping each other accountable. Great for couples, friends, or training buddies who want professional guidance without the solo price tag.',      
    bookingLink: 'https://cal.com/elmarfitness/partner-training-session',
    bookingLabel: 'Schedule a Session',
    image: '/partner.png',
    classification: 'in-person',
    highlights: ['Individualized programs', 'Partner accountability', 'Fun competition', 'Shared sessions'],
  },
  {
    name: 'online-coaching',
    service: 'Online Coaching',
    price: 'As low as $150/month',
    description: 'Elite training, anywhere. I build custom AI-enhanced workout programs tailored to your equipment, schedule, and goals. Weekly check-ins, form video reviews, and nutrition guidance — all through an app. Perfect for serious athletes who want pro-level coaching without the gym commute.',      
    bookingLink: 'https://cal.com/elmarfitness/online-coaching-call',
    bookingLabel: 'Schedule a Call',
    image: '/online.png',
    classification: 'online',
    highlights: ['Custom workout app', 'Weekly video check-ins', 'Nutrition guidance', '24/7 messaging'],
  },
  {
    name: 'nutrition',
    service: 'Meal Planning',
    price: ' As low as $100/month',
    description: 'No starving, no fad diets. I build meal plans that fit your lifestyle, preferences, and goals — whether that\'s losing fat, building muscle, or just eating better. Based on your TDEE, food preferences, and schedule. Includes macro tracking and grocery lists.',      
    bookingLink: 'https://cal.com/elmarfitness/nutrition-meal-planning-call',
    bookingLabel: 'Schedule a Call',
    image: '/meal.png',
    classification: 'online',
    highlights: ['Personalized macros', 'Flexible dieting', 'Grocery lists', 'Recipe suggestions'],
  },
];
